name: Actions Commands

on: [push]

jobs: 
  run-github-command:
    runs-on: ubuntu-latest
    steps: github checkout
      - name: Checkout github repo
        uses: actions/checkout@v2
        run: |
          pwd
          ls -a         
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"