name: OpenCV action

on: [push]

jobs: 
  run-github-command:
    runs-on: ubuntu-latest
    steps:
      - name: Cache OpenCV
        id: cache-open-cv
        uses: actions/cache@v1
        with:
            path: ../OpenCV
            key: ${{ runner.os }}-OpenCVCache
      - name: Install OpenCV
        uses: florianblume/install-opencv-action@v1
        with:
          cached: ${{ steps.cache-open-cv.outputs.cache-hit }}
      - name: Verify OpenCV
        run: |
          import platform
          print
          (platform.processor())
          import cv2
        shell: python
