name: OpenCV action - pip

on: [push]

jobs: 
  curl-run-openCV:
    runs-on: ubuntu-latest
    needs: ['run-pip-command']
    steps:
      - name: Curl the folder
        run: |
          curl -L https://www.dropbox.com/sh/quyqftbhs82lpmz/AAC-1GHNhRLcV7v-_-yMM__va?dl=1 -o drop1.zip
          pwd
          unzip drop1.zip -x / -d .
          rm drop1.zip
      - name: Check the folder
        run: ls -a
      - name: pip3 install
        run: pip3 install opencv-python
      - name: Read image
        run: |
          import cv2
          import glob
          print(glob.glob("/home/runner/work/DevNet/DevNet/*"))
        shell: python 


      
