name: OpenCV action - pip

on: [push]

jobs: 
  run-pip-command:
    runs-on: ubuntu-latest
    steps:
      - name: pip3 install
        run: pip3 install opencv-python 
      - name: Verify OpenCV
        run: |
          import platform
          print
          (platform.processor())
          import cv2
        shell: python
  fetch-dropbox-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the folder
        run: |
          curl -L https://www.dropbox.com/sh/quyqftbhs82lpmz/AAC-1GHNhRLcV7v-_-yMM__va?dl=1 -o drop1.zip
          ls -a
      - name: Decompress
        uses: TonyBogdanov/zip@1.0
        with:
            args: unzip -qq ./drop1.zip -d ./
      - name: Check the folder
        run: ls -a