name: Shell Commands

on: [push, pull ]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Welcome back, Mr. Reese"
      - name: multiline script
        run: |
        df -h
        du -sh