name: Shell Commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Welcome back, Mr. Reese"
      - name: multiline script
        run: |
        df -h;
        ls -a;
      - name: python command
        run: |
          import platform
          print
          (platform.processor())
        shell: python